import './globals.css'
import Header from './components/header'
import Footer from './components/footer'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Inter } from 'next/font/google'

const bebasNeue = localFont({ src: './fonts/bebasNeue-regular.woff2' })
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Siembra Sana',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
	<head>
		{/* <link
      	  	rel="preload"
      	  	href="/fonts/bebasNeue-regular.woff2"
      	  	as="font"
      	  	crossOrigin=""
      	  	type="font/woff2"
      	/> */}
	</head>
      <body className={inter.className}>
		<Header />
		{children}
		<Footer />
	  </body>
    </html>
  )
}
